[package]
name = "lyric-adder"
version = "0.1.0"
edition = "2024"

[dependencies]
lofty = "0.22.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ureq = { version = "3.0.12", features = ["json"] }
url = "2.5.4"
